### ISSUE TITLE
Need workshop content

### ISSUE THREAD

**Issue by carols10cents** [rust-community/rustbridge#2] opened 2016-05-18 16:33 UTC
Some general workshop thoughts here: https://github.com/rust-community/team/issues/11

**Comment by broesamle** [comment] 2016-05-24 10:09
One aspect that strikes me as important (if not crucial) is to get the newcomer into the "mechanistic" ways our computing architectures work. From my course experience they often struggle in thinking "too associative" rather than strictly according to well-defined computational processes.

In the beginning of a beginners-beginners tutorial I would refrain from talking about stacks, heaps, registers, pointers etc. The challenge is then, obviously, to come up with good metaphors which would carry on into the later course, when things get more complex (and we, of course have to introduce them).  

Alternative would be: JUMP into complexity right away, but warn about the complexity. (That worked in a face to face course on Python, with a highly motivated group.) I don't recommend it, here!!

**Comment by Manishearth** [comment] 2016-05-24 10:11
I've been wanting to write some blog posts that introduce Rust through architecture; might get to them soon.

**Comment by hjr3** [comment] 2016-06-02 16:47
@erickt was asking for website material. I have started a blog series on creating a webservice in Rust. I have two posts and am currently working on the third:

* [Creating a basic webservice in Rust](http://hermanradtke.com/2016/05/16/creating-a-basic-webservice-in-rust.html)
* [Connecting a webservice to a database in Rust](http://hermanradtke.com/2016/05/23/connecting-webservice-database-rust.html)
* Error handling and Logging for a Webservice in Rust - in progress

If deemed useful, I am happy to convert/modify this content into the appropriate format for Rust Bridge.

**Comment by erickt** [comment] 2016-06-15 16:57
@wycats is working on a [text-based adventure tutorial](https://github.com/tildeio/learning-rust).

**Comment by carols10cents** [comment] 2016-06-15 16:59
So I kinda started over a year ago working on content for a tutorial using piston, and got as far as a piston hello world... https://github.com/carols10cents/game-dev/blob/master/part1.md

I'm happy to contribute that and collaborate with people on continuing, but i clearly can't be trusted to lead moving this forward given that I haven't progressed very far with it ;)

Some people like @bstrie have concerns about the approachability of piston, but I really really like that you can get something that you can show off to people really fast. Having progress on making something that you can *see* is really important for early learning motivation imo/e.

**Comment by skade** [comment] 2016-06-15 16:59
Also see #6

**Comment by carols10cents** [comment] 2016-06-15 17:00
Also, I'm not a beginner/non-programmer and I don't think this compiles anymore, but I wrote a playable game without having known piston in 2 days: https://github.com/carols10cents/color-game/commits/master

**Comment by carols10cents** [comment] 2016-06-15 17:01
Also also, we could totally have multiple workshop focuses-- railsbridge has a few projects. Nothing stopping that except time of people to write the tutorials...

**Comment by skade** [comment] 2016-06-15 17:03
@carols10cents Yep, we should definitely have that. We could even run multiple at one event, as long as groups pick them well.

**Comment by tomaka** [comment] 2016-06-23 06:15
I promised on IRC to write something here about the ecosystem but totally forgot.

Anyway, one of my concerns about Piston is that it's slow. It is not slow by itself, but it is slowed down by the graphics driver of the system.

Any professional game engine that uses OpenGL today uses various optimization techniques in order to reduce the amount of operations that the driver has to perform. Piston doesn't do that because of modularity-related and code-design-related concerns.
On my modern gaming machine, a game running Piston starts to drop under 60fps if you draw more than around 2000 sprites per frame. With correct optimization techniques, it can reach about one million sprites before going below that threshold (500x faster). And even then it's only limited by the transfer rate of the PCI-Express bus between the CPU and the GPU, so if you sacrifice usability you can probably go much higher.

Of course the fact that something is slow is not a problem per se. The problem is that Rust is and has always been advertised as a fast language.
If I was a beginner game developer, got taught how to write a game with a library officially endorsed by a Rust team, and discovered that it started to lag after 2000 sprites I'd seriously doubt that Rust would be able to run a AAA game.

**Comment by skade** [comment] 2016-06-23 09:25
@tomaka Please note that we are talking about people with close to zero knowledge in programming. It will probably take them a sizable amount of time until they end up in the ranges you think about and "fast" will probably not be the category they think in in the first moment.

I do agree though that advertising a framework might gear people towards that one. One of our ideas was building a small sandbox that hides all inner details for some simple manipulation of visual primitives. (think: "let's draw chess") I think we would not end up using or introducing piston (or any other tool) directly.

**Comment by tomaka** [comment] 2016-06-23 09:34
> One of our ideas was building a small sandbox that hides all inner details for some simple manipulation of visual primitives. (think: "let's draw chess") I think we would not end up using or introducing piston (or any other tool) directly.

That would be a good solution.

**Comment by Manishearth** [comment] 2016-06-23 11:22
> One of our ideas was building a small sandbox that hides all inner details for some simple manipulation of visual primitives. 

In my first year of college the intro CS course used something called "simplecpp". This was basically LOGO (turtle graphics), but with C++ -- you had turtle objects and could move them by calling methods, etc. There's a lot you can do with these, and it's quite fun. We could try something similar?

**Comment by broesamle** [comment] 2016-06-23 12:18
fits well with parallel processing at some point 
: )


Martin Br:osamle     m-broe.de

-------- Ursprüngliche Nachricht --------
Von: Manish Goregaokar <notifications@github.com> 
Datum: 23.06.2016  13:22  (GMT+01:00) 
An: rust-community/rustbridge <rustbridge@noreply.github.com> 
Cc: "Martin Br:osamle" <info@m-broe.de>,Comment <comment@noreply.github.com> 
Betreff: Re: [rust-community/rustbridge] Need workshop content (#2) 
 
One of our ideas was building a small sandbox that hides all inner details for some simple manipulation of visual primitives.

In my first year of college the intro CS course used something called "simplecpp". This was basically LOGO (turtle graphics), but with C++ -- you had turtle objects and could move them by calling methods, etc. There's a lot you can do with these, and it's quite fun. We could try something similar?

**Comment by skade** [comment] 2016-06-23 15:47
See #6 and #7 and https://github.com/rust-community/team/issues/11 on this.

**Comment by skade** [comment] 2016-06-23 15:48
Also, most importantly the minutes from #7: https://github.com/rust-lang/meeting-minutes/blob/master/rustbridge/2016-06-22.txt

**Comment by steveklabnik** [comment] 2016-06-23 15:53
Yesterday, @ashleygwilliams mentioned that maybe a URL shortener might be an interesting project: still web, but not too complex

**Comment by broesamle** [comment] 2016-06-24 20:01
how about a (recursive multithreaded) mondriannpattern painter? you can define whether the reference to the part of the canvas gets deligated (borrowed or given away completely) depending on how much central constrained you wabt your mondriann to be--etc

**Comment by broesamle** [comment] 2016-07-12 19:45
... added a branch [workshop-materials](https://github.com/rust-community/rustbridge/tree/workshop-materials) and set up a [dir](https://github.com/rust-community/rustbridge/tree/workshop-materials/workshops/)

**Comment by kainino0x** [comment] 2016-08-13 23:01
Our [CIS 198 course](http://cis198-2016s.github.io/schedule/) has a few assignments that might make useful starting points for workshops (steal whatever you want). Many of these are probably shorter than one full workshop but still might provide inspiration:
* [RPN calculator (simple input parsing, stack)](https://github.com/cis198-2016s/homework/tree/master/hw04)
* [Hyper BBS and bot (hyper server/client, tcp, file i/o)](https://github.com/cis198-2016s/homework/tree/master/hw06)
* [multithreaded WebSocket chat server](https://github.com/cis198-2016s/homework/tree/master/hw07) - for this assignment, the HTML/JS client was provided to the students
    * In this assignment, each student had their own _server_. But it could be really fun in a workshop for everyone to write _clients_ for a server hosted by the workshop leaders, so they can talk to each other. Each student could even write a chat bot. (It wouldn't be as interesting from the multithreading side, though.)

(We can provide solutions by request for any of the homework assignments.)

**Comment by aepsil0n** [comment] 2016-08-30 10:38
I think we can close this thread by now, since the effort has been split into a bunch of other issues.

**Closed** 2016-09-02 14:13 UTC
